"""add record

Revision ID: 1b570aae20ba
Revises: 37a0c675900
Create Date: 2015-08-11 12:50:08.141511

"""

# revision identifiers, used by Alembic.
revision = '1b570aae20ba'
down_revision = '37a0c675900'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('item', sa.String(length=32), nullable=True),
    sa.Column('item_id', sa.String(length=32), nullable=True),
    sa.Column('field', sa.String(length=32), nullable=True),
    sa.Column('value', sa.String(length=32), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_record_username'), 'record', ['username'], unique=True)
    op.drop_table('Record')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Record',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('item', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('item_id', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('field', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('value', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('date', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_index(op.f('ix_record_username'), table_name='record')
    op.drop_table('record')
    ### end Alembic commands ###
