"""change iprange to ipsubnet

Revision ID: 2019c54cd10a
Revises: 58537aad0c78
Create Date: 2015-08-07 19:35:57.385630

"""

# revision identifiers, used by Alembic.
revision = '2019c54cd10a'
down_revision = '58537aad0c78'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ipsubnet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subnet', sa.String(length=64), nullable=True),
    sa.Column('s_ip', sa.String(length=64), nullable=True),
    sa.Column('e_ip', sa.String(length=64), nullable=True),
    sa.Column('netmask', sa.String(length=64), nullable=True),
    sa.Column('site', sa.String(length=64), nullable=True),
    sa.Column('client', sa.String(length=64), nullable=True),
    sa.Column('remark', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ipsubnet_subnet'), 'ipsubnet', ['subnet'], unique=True)
    op.drop_table('iprange')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iprange',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('s_ip', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('e_ip', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('netmask', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('site', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('client', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('remark', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('ip_r', mysql.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_index(op.f('ix_ipsubnet_subnet'), table_name='ipsubnet')
    op.drop_table('ipsubnet')
    ### end Alembic commands ###
