"""site tales add location

Revision ID: 2ac72067e1e0
Revises: 475d1b2c7d76
Create Date: 2015-08-04 07:35:29.470222

"""

# revision identifiers, used by Alembic.
revision = '2ac72067e1e0'
down_revision = '475d1b2c7d76'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('location', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site', 'location')
    ### end Alembic commands ###
