"""user table

Revision ID: 2e424fb27cda
Revises: None
Create Date: 2015-07-31 15:11:35.415010

"""

# revision identifiers, used by Alembic.
revision = '2e424fb27cda'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
