"""record value 500

Revision ID: 2fcbf835a6ea
Revises: 45264f4433e
Create Date: 2015-08-12 09:06:29.982244

"""

# revision identifiers, used by Alembic.
revision = '2fcbf835a6ea'
down_revision = '45264f4433e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
