"""change record item

Revision ID: 31f225a2dc9c
Revises: 3d22ceeededa
Create Date: 2015-08-11 18:33:04.652393

"""

# revision identifiers, used by Alembic.
revision = '31f225a2dc9c'
down_revision = '3d22ceeededa'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('item', sa.String(length=32), nullable=True))
    op.drop_column('record', 'field')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('field', mysql.VARCHAR(length=32), nullable=True))
    op.drop_column('record', 'item')
    ### end Alembic commands ###
