"""change record item

Revision ID: 3618b6da46b5
Revises: d53335ffa41
Create Date: 2015-08-12 09:28:09.385551

"""

# revision identifiers, used by Alembic.
revision = '3618b6da46b5'
down_revision = 'd53335ffa41'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('values', sa.Text(length=500), nullable=True))
    op.drop_column('record', 'value')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('value', mysql.VARCHAR(length=32), nullable=True))
    op.drop_column('record', 'values')
    ### end Alembic commands ###
