"""add iprange

Revision ID: 3698b9015784
Revises: None
Create Date: 2015-08-07 16:09:43.867635

"""

# revision identifiers, used by Alembic.
revision = '3698b9015784'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('iprange', sa.Column('ip', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_iprange_ip'), 'iprange', ['ip'], unique=True)
    op.drop_column('iprange', 'iprange')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('iprange', sa.Column('iprange', mysql.VARCHAR(length=256), nullable=True))
    op.drop_index(op.f('ix_iprange_ip'), table_name='iprange')
    op.drop_column('iprange', 'ip')
    ### end Alembic commands ###
