"""add Record

Revision ID: 37a0c675900
Revises: 1a5deb4b2b20
Create Date: 2015-08-11 12:30:09.987271

"""

# revision identifiers, used by Alembic.
revision = '37a0c675900'
down_revision = '1a5deb4b2b20'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('item', sa.String(length=32), nullable=True),
    sa.Column('item_id', sa.String(length=32), nullable=True),
    sa.Column('field', sa.String(length=32), nullable=True),
    sa.Column('value', sa.String(length=32), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Record_username'), 'Record', ['username'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Record_username'), table_name='Record')
    op.drop_table('Record')
    ### end Alembic commands ###
