"""change ippool

Revision ID: 37e91e07ade2
Revises: 2019c54cd10a
Create Date: 2015-08-08 10:25:33.720637

"""

# revision identifiers, used by Alembic.
revision = '37e91e07ade2'
down_revision = '2019c54cd10a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ippool', sa.Column('subnet', sa.String(length=64), nullable=True))
    op.drop_column('ippool', 'ip_r')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ippool', sa.Column('ip_r', mysql.VARCHAR(length=64), nullable=True))
    op.drop_column('ippool', 'subnet')
    ### end Alembic commands ###
