"""change record username

Revision ID: 3bafb67190d0
Revises: 1b570aae20ba
Create Date: 2015-08-11 16:31:15.246083

"""

# revision identifiers, used by Alembic.
revision = '3bafb67190d0'
down_revision = '1b570aae20ba'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_record_username', table_name='record')
    op.create_index(op.f('ix_record_username'), 'record', ['username'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_record_username'), table_name='record')
    op.create_index('ix_record_username', 'record', ['username'], unique=True)
    ### end Alembic commands ###
