"""change record item

Revision ID: 45264f4433e
Revises: 31f225a2dc9c
Create Date: 2015-08-11 18:37:51.628203

"""

# revision identifiers, used by Alembic.
revision = '45264f4433e'
down_revision = '31f225a2dc9c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
