"""add site tables

Revision ID: 475d1b2c7d76
Revises: 2e424fb27cda
Create Date: 2015-08-03 18:57:57.095634

"""

# revision identifiers, used by Alembic.
revision = '475d1b2c7d76'
down_revision = '2e424fb27cda'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site', sa.String(length=64), nullable=True),
    sa.Column('isp', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=64), nullable=True),
    sa.Column('contact', sa.String(length=64), nullable=True),
    sa.Column('remark', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_site'), 'site', ['site'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_site_site'), table_name='site')
    op.drop_table('site')
    ### end Alembic commands ###
