"""change record item

Revision ID: 4f755a552985
Revises: 3618b6da46b5
Create Date: 2015-08-12 09:34:23.753910

"""

# revision identifiers, used by Alembic.
revision = '4f755a552985'
down_revision = '3618b6da46b5'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('value', sa.String(length=600), nullable=True))
    op.drop_column('record', 'values')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('values', mysql.TEXT(), nullable=True))
    op.drop_column('record', 'value')
    ### end Alembic commands ###
