"""empty message

Revision ID: 51cc5d781f62
Revises: 9bf4071efa0
Create Date: 2015-07-24 16:58:32.117576

"""

# revision identifiers, used by Alembic.
revision = '51cc5d781f62'
down_revision = '9bf4071efa0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
