"""change cabinet

Revision ID: 526653929d77
Revises: 58840f599ed2
Create Date: 2015-08-09 17:59:36.614831

"""

# revision identifiers, used by Alembic.
revision = '526653929d77'
down_revision = '58840f599ed2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
