"""site tales add location

Revision ID: 5453560ef875
Revises: 2ac72067e1e0
Create Date: 2015-08-05 16:57:19.350772

"""

# revision identifiers, used by Alembic.
revision = '5453560ef875'
down_revision = '2ac72067e1e0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rack',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rack', sa.String(length=64), nullable=True),
    sa.Column('site', sa.String(length=64), nullable=True),
    sa.Column('count', sa.String(length=32), nullable=True),
    sa.Column('power', sa.String(length=32), nullable=True),
    sa.Column('client', sa.String(length=64), nullable=True),
    sa.Column('c_time', sa.Date(), nullable=True),
    sa.Column('e_time', sa.Date(), nullable=True),
    sa.Column('remark', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rack_rack'), 'rack', ['rack'], unique=False)
    op.create_index(op.f('ix_rack_site'), 'rack', ['site'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rack_site'), table_name='rack')
    op.drop_index(op.f('ix_rack_rack'), table_name='rack')
    op.drop_table('rack')
    ### end Alembic commands ###
