"""add ippool

Revision ID: 58537aad0c78
Revises: 3698b9015784
Create Date: 2015-08-07 18:49:05.175512

"""

# revision identifiers, used by Alembic.
revision = '58537aad0c78'
down_revision = '3698b9015784'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ippool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('netmask', sa.String(length=64), nullable=True),
    sa.Column('gateway', sa.String(length=64), nullable=True),
    sa.Column('ip_r', sa.String(length=64), nullable=True),
    sa.Column('site', sa.String(length=64), nullable=True),
    sa.Column('client', sa.String(length=64), nullable=True),
    sa.Column('remark', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ippool_ip'), 'ippool', ['ip'], unique=True)
    op.add_column(u'iprange', sa.Column('ip_r', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_iprange_ip_r'), 'iprange', ['ip_r'], unique=True)
    op.drop_index('ix_iprange_ip', table_name='iprange')
    op.drop_column(u'iprange', 'ip')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'iprange', sa.Column('ip', mysql.VARCHAR(length=64), nullable=True))
    op.create_index('ix_iprange_ip', 'iprange', ['ip'], unique=True)
    op.drop_index(op.f('ix_iprange_ip_r'), table_name='iprange')
    op.drop_column(u'iprange', 'ip_r')
    op.drop_index(op.f('ix_ippool_ip'), table_name='ippool')
    op.drop_table('ippool')
    ### end Alembic commands ###
