"""add sales clinet

Revision ID: 591514729f36
Revises: 4f755a552985
Create Date: 2015-08-13 12:18:32.338539

"""

# revision identifiers, used by Alembic.
revision = '591514729f36'
down_revision = '4f755a552985'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('contact', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('remark', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_username'), 'client', ['username'], unique=True)
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('contact', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('remark', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_username'), 'sales', ['username'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_username'), table_name='sales')
    op.drop_table('sales')
    op.drop_index(op.f('ix_client_username'), table_name='client')
    op.drop_table('client')
    ### end Alembic commands ###
