"""empty message

Revision ID: 9bf4071efa0
Revises: None
Create Date: 2015-07-24 16:54:07.523443

"""

# revision identifiers, used by Alembic.
revision = '9bf4071efa0'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stat_0')
    op.drop_table('cmdb')
    op.drop_table('stat_2')
    op.drop_table('stat_1')
    op.drop_table('stat_3')
    op.add_column('users', sa.Column('role', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.create_table('stat_3',
    sa.Column('id', mysql.INTEGER(display_width=11, unsigned=True), nullable=False),
    sa.Column('host', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('mem_free', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('mem_usage', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('mem_total', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('load_avg', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('time', mysql.BIGINT(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('stat_1',
    sa.Column('id', mysql.INTEGER(display_width=11, unsigned=True), nullable=False),
    sa.Column('host', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('mem_free', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('mem_usage', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('mem_total', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('load_avg', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('time', mysql.BIGINT(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('stat_2',
    sa.Column('id', mysql.INTEGER(display_width=11, unsigned=True), nullable=False),
    sa.Column('host', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('mem_free', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('mem_usage', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('mem_total', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('load_avg', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('time', mysql.BIGINT(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('cmdb',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('server', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('memory', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('stat_0',
    sa.Column('id', mysql.INTEGER(display_width=11, unsigned=True), nullable=False),
    sa.Column('host', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('mem_free', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('mem_usage', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('mem_total', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('load_avg', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('time', mysql.BIGINT(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
