"""add sales

Revision ID: cf916d0cc4a
Revises: 526653929d77
Create Date: 2015-08-10 22:39:24.310274

"""

# revision identifiers, used by Alembic.
revision = 'cf916d0cc4a'
down_revision = '526653929d77'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cabinet', sa.Column('expire_time', sa.Date(), nullable=True))
    op.add_column('cabinet', sa.Column('sales', sa.String(length=32), nullable=True))
    op.add_column('cabinet', sa.Column('start_time', sa.Date(), nullable=True))
    op.drop_column('cabinet', 'salesman')
    op.drop_column('cabinet', 'e_time')
    op.drop_column('cabinet', 'c_time')
    op.add_column('ipsubnet', sa.Column('end_ip', sa.String(length=64), nullable=True))
    op.add_column('ipsubnet', sa.Column('expire_time', sa.Date(), nullable=True))
    op.add_column('ipsubnet', sa.Column('sales', sa.String(length=32), nullable=True))
    op.add_column('ipsubnet', sa.Column('start_ip', sa.String(length=64), nullable=True))
    op.add_column('ipsubnet', sa.Column('start_time', sa.Date(), nullable=True))
    op.drop_column('ipsubnet', 's_ip')
    op.drop_column('ipsubnet', 'e_ip')
    op.add_column('rack', sa.Column('expire_time', sa.Date(), nullable=True))
    op.add_column('rack', sa.Column('sales', sa.String(length=32), nullable=True))
    op.add_column('rack', sa.Column('start_time', sa.Date(), nullable=True))
    op.drop_column('rack', 'e_time')
    op.drop_column('rack', 'c_time')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rack', sa.Column('c_time', sa.DATE(), nullable=True))
    op.add_column('rack', sa.Column('e_time', sa.DATE(), nullable=True))
    op.drop_column('rack', 'start_time')
    op.drop_column('rack', 'sales')
    op.drop_column('rack', 'expire_time')
    op.add_column('ipsubnet', sa.Column('e_ip', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('ipsubnet', sa.Column('s_ip', mysql.VARCHAR(length=64), nullable=True))
    op.drop_column('ipsubnet', 'start_time')
    op.drop_column('ipsubnet', 'start_ip')
    op.drop_column('ipsubnet', 'sales')
    op.drop_column('ipsubnet', 'expire_time')
    op.drop_column('ipsubnet', 'end_ip')
    op.add_column('cabinet', sa.Column('c_time', sa.DATE(), nullable=True))
    op.add_column('cabinet', sa.Column('e_time', sa.DATE(), nullable=True))
    op.add_column('cabinet', sa.Column('salesman', mysql.VARCHAR(length=64), nullable=True))
    op.drop_column('cabinet', 'start_time')
    op.drop_column('cabinet', 'sales')
    op.drop_column('cabinet', 'expire_time')
    ### end Alembic commands ###
