"""change record item

Revision ID: d53335ffa41
Revises: 2fcbf835a6ea
Create Date: 2015-08-12 09:21:43.309435

"""

# revision identifiers, used by Alembic.
revision = 'd53335ffa41'
down_revision = '2fcbf835a6ea'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
